# Generated by Django 6.0.3 on 2026-03-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
